/* C++ C_MAKE_TEMP_PKG - Interfaces to make type node utilities. */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY
 *
 *  03.01.90  PKT  000  Original.
 *
 ***********************************************************************/

declare

MAKE_POINTER_TYPE		entry    (type (SHORT_T))
				returns  (type (NID_T))
				external (X_MAKE_POINTER_TYPE);
