/* C++ CXX_SAVE_GLOBAL_DATA_PKG - Save global data */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY
 *
 *  02.01.91  DGM  000  Original.
 *
 ***********************************************************************/

declare

SAVE_CXXFE_GLOBAL_DATA		entry
				external (X_SAVE_CXXFE_GLOBAL_DATA),
SET_CXXFE_GLOBAL_DATA		entry
				external (X_SET_CXXFE_GLOBAL_DATA);

