/* C++ C_TOKEN_POD_DEBUG_PKG - Interface to token pod debugging module */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY
 *
 *  11.08.89  DGM  Original.
 *
 ***********************************************************************/

declare

TDUMP		entry (pointer)
		external,

TLDUMP		entry (pointer)
		external;

