########################################################################
# PROGRAM:	VALID System wirelist program
# BOARD:	AUGAT 8136-HPWG1 Universal Panel (dense pack)
# FILE:		Makefile
# AUTHOR:	David Michaels (david@ll-sst)
# DATE:		December 1984
########################################################################

########################################################################
#		Directories
########################################################################

MAIN_DIR =	../..

########################################################################
#		Files
########################################################################

CFILES =	board.c

OFILES =	board.o

ALL_CFILES =	$(CFILES)

ALL_OFILES =	$(OFILES)

########################################################################
#		Flags
########################################################################

INCLUDES =	$(MAIN_INCLUDES) -I$(MAIN_DIR)

CFLAGS =	-O $(INCLUDES)

########################################################################
#		Make Dependencies
########################################################################

all:		$(ALL_CFILES)
		$(CC) $(CFLAGS) -c $(ALL_CFILES)

board.o:	board.c
		$(CC) $(CFLAGS) -c board.c

########################################################################
#		Utilities
########################################################################

list:
		ipf -2 $(ALL_CFILES) Makefile

tape:
		tar cv $(ALL_CFILES) Makefile

protect:
		chmod 444 $(ALL_CFILES) $(HEADS)

unprotect:
		chmod 644 $(ALL_CFILES) $(HEADS)

clean:
		rm $(ALL_OFILES)
