/* C++ C_RUN_CPP_PKG - Run preprocessor interface */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY               [ Update the VERSION__ string below ]
 *
 *  09.14.90  DGM  001  Changed include file names and VOP names.
 *  06.08.90  DGM  000  Original.
 *
 ***********************************************************************/

declare

RUN_PP_ONLY	entry
		returns  (type (BOOL_T))
		external (X_RUN_PP_ONLY);

