/* C++ C_TYPE_UTILITY_PKG - Type utility package interface */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY
 *
 *  01.05.90  DGM  000  Original.
 *
 ***********************************************************************/

/***********************************************************************
/* This declares the type mapping arrays IS_INTEGRAL, IS_ARITHMETIC,
/* IS_SCALAR, IS_CONST, IS_VOLATILE, and IS_NOALIAS.
 ***********************************************************************/

/* ---------------------------------------------------------------------
/* Required include files
/* ------------------------------------------------------------------- */

/* %include C_STANDARD_DEFS_IN;     */
/* %include C_EXTERNAL_NAME_MAP_IN; */
/* %include C_SYMBOL_TABLE_DEFS_IN; */

/* ---------------------------------------------------------------------
/* Include files
/* ------------------------------------------------------------------- */

%include C_TYPE_MAP_IN;

