
/***********************************************************************
* PROGRAM:	VALID Applications Library
* FILE:		valid.h
* AUTHOR:	David Michaels (david@ll-sst)
* DATE:		December 1984
***********************************************************************/

/* VALID file function declarations */

char	*vf_brdlsthdr();
char	*vf_ged();
char	*vf_lsthdr();
char	*vf_pgnd();
char	*vf_pkgdesc();
char	*vf_pkgdir();
char	*vf_pkgfile();
char	*vf_pkgmap();
char	*vf_prtmap();
char	*vf_sysdir();
char	*vf_xnet();
char	*vf_xprt();
