//	rcdef.cpp
//
//	Allegris Foundation library resource definitions
//
//  Allegris Foundation 1.1.00
//	Copyright (c) 1997 by INTERSOLV, Inc.
//	+-----------------------------------------------------------------+
//	| This product is the property of INTERSOLV, Inc. and is licensed |
//	| pursuant to a written license agreement.  No portion of  this   |
//	| product may be reproduced without the written permission of     |
//	| INTERSOLV, Inc. except pursuant to the license agreement.       |
//	+-----------------------------------------------------------------+
//
//	Revision History:
//	-----------------
//	01/30/97 dgm	Original.
// --------------------------------------------------------------------------

#define   CV_RC_LIBRARY_DEFINE
#include "cv.rc"
