/* C++ CXX_LEXER_TOKENS_PKG - Interface to the lexer package tokens */

/***********************************************************************
 * This product is the property of Language Processors, Inc. and is    *
 * licensed pursuant to a written license agreement.  No portion of    *
 * this product may be reproduced without the written permission of    *
 * Language Processors, Inc. except pursuant to the license agreement. *
 ***********************************************************************/

/***********************************************************************
 *
 *  LPI EDIT HISTORY
 *
 *  09.25.90  DGM  002  Preprocessor include file name changes.
 *  09.14.90  DGM  001  Changed include file names and VOP names.
 *
 ***********************************************************************/

%include CXX_PP_TOKEN_POD_IN;
%include CXX_LEXER_IN;

